/********************************************************************
* libDiffAnalysis_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error libDiffAnalysis_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablelibDiffAnalysis_Dict();
extern void G__cpp_setup_inheritancelibDiffAnalysis_Dict();
extern void G__cpp_setup_typetablelibDiffAnalysis_Dict();
extern void G__cpp_setup_memvarlibDiffAnalysis_Dict();
extern void G__cpp_setup_globallibDiffAnalysis_Dict();
extern void G__cpp_setup_memfunclibDiffAnalysis_Dict();
extern void G__cpp_setup_funclibDiffAnalysis_Dict();
extern void G__set_cpp_environmentlibDiffAnalysis_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./DiffJetXFCalc_Inc.h"
#include "./DiffJetXFANCalc_6pt_Inc.h"
#include "./RunDiffJetTreeMaker_zerobias.h"
#include "./TStFmsHotChDB.h"
#include "./DiffJetXFCalc_EastRPnew.h"
#include "./TStRunList.h"
#include "./DiffJetXFANCalc_6pt_East_getChi2AndConst.h"
#include "./DiffJetAnaTreeQaRun15New.h"
#include "./DiffJetXFANCalc_6pt_East.h"
#include "./DiffJetXFCalc_WestRPnew.h"
#include "./DiffJetXFANCalc_6pt_RG.h"
#include "./RunDiffJetTreeMaker_FMS.h"
#include "./RunDiffJetTreeMaker.h"
#include "./DiffJetXFANCalc_6pt_SE.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__libDiffAnalysis_DictLN_TClass;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TBuffer;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TMemberInspector;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TObject;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TString;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_string;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TStFmsHotChDB;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TEntryList;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TStRunList;

/* STUB derived class for protected member access */
