//
// File generated by rootcint at Thu Feb 13 17:18:32 2025

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME libDiffAnalysis_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "libDiffAnalysis_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void TStFmsHotChDB_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TStFmsHotChDB(void *p = 0);
   static void *newArray_TStFmsHotChDB(Long_t size, void *p);
   static void delete_TStFmsHotChDB(void *p);
   static void deleteArray_TStFmsHotChDB(void *p);
   static void destruct_TStFmsHotChDB(void *p);
   static void streamer_TStFmsHotChDB(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::TStFmsHotChDB*)
   {
      ::TStFmsHotChDB *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TStFmsHotChDB >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TStFmsHotChDB", ::TStFmsHotChDB::Class_Version(), "././TStFmsHotChDB.h", 15,
                  typeid(::TStFmsHotChDB), ::ROOT::DefineBehavior(ptr, ptr),
                  &::TStFmsHotChDB::Dictionary, isa_proxy, 0,
                  sizeof(::TStFmsHotChDB) );
      instance.SetNew(&new_TStFmsHotChDB);
      instance.SetNewArray(&newArray_TStFmsHotChDB);
      instance.SetDelete(&delete_TStFmsHotChDB);
      instance.SetDeleteArray(&deleteArray_TStFmsHotChDB);
      instance.SetDestructor(&destruct_TStFmsHotChDB);
      instance.SetStreamerFunc(&streamer_TStFmsHotChDB);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::TStFmsHotChDB*)
   {
      return GenerateInitInstanceLocal((::TStFmsHotChDB*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TStFmsHotChDB*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

namespace ROOTDict {
   void TStRunList_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TStRunList(void *p = 0);
   static void *newArray_TStRunList(Long_t size, void *p);
   static void delete_TStRunList(void *p);
   static void deleteArray_TStRunList(void *p);
   static void destruct_TStRunList(void *p);
   static void streamer_TStRunList(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::TStRunList*)
   {
      ::TStRunList *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TStRunList >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TStRunList", ::TStRunList::Class_Version(), "././TStRunList.h", 16,
                  typeid(::TStRunList), ::ROOT::DefineBehavior(ptr, ptr),
                  &::TStRunList::Dictionary, isa_proxy, 0,
                  sizeof(::TStRunList) );
      instance.SetNew(&new_TStRunList);
      instance.SetNewArray(&newArray_TStRunList);
      instance.SetDelete(&delete_TStRunList);
      instance.SetDeleteArray(&deleteArray_TStRunList);
      instance.SetDestructor(&destruct_TStRunList);
      instance.SetStreamerFunc(&streamer_TStRunList);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::TStRunList*)
   {
      return GenerateInitInstanceLocal((::TStRunList*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TStRunList*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr TStFmsHotChDB::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *TStFmsHotChDB::Class_Name()
{
   return "TStFmsHotChDB";
}

//______________________________________________________________________________
const char *TStFmsHotChDB::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TStFmsHotChDB*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TStFmsHotChDB::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TStFmsHotChDB*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TStFmsHotChDB::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TStFmsHotChDB*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TStFmsHotChDB::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TStFmsHotChDB*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
atomic_TClass_ptr TStRunList::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *TStRunList::Class_Name()
{
   return "TStRunList";
}

//______________________________________________________________________________
const char *TStRunList::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TStRunList*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TStRunList::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TStRunList*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TStRunList::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TStRunList*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TStRunList::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TStRunList*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void TStRunList::Streamer(TBuffer &R__b)
{
   // Stream an object of class TStRunList.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> runList;
      R__b >> missingRunList;
      R__b.CheckByteCount(R__s, R__c, TStRunList::IsA());
   } else {
      R__c = R__b.WriteVersion(TStRunList::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << runList;
      R__b << missingRunList;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TStRunList::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TStRunList.
      TClass *R__cl = ::TStRunList::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*runList", &runList);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*missingRunList", &missingRunList);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_TStRunList(void *p) {
      return  p ? new(p) ::TStRunList : new ::TStRunList;
   }
   static void *newArray_TStRunList(Long_t nElements, void *p) {
      return p ? new(p) ::TStRunList[nElements] : new ::TStRunList[nElements];
   }
   // Wrapper around operator delete
   static void delete_TStRunList(void *p) {
      delete ((::TStRunList*)p);
   }
   static void deleteArray_TStRunList(void *p) {
      delete [] ((::TStRunList*)p);
   }
   static void destruct_TStRunList(void *p) {
      typedef ::TStRunList current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_TStRunList(TBuffer &buf, void *obj) {
      ((::TStRunList*)obj)->::TStRunList::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::TStRunList

//______________________________________________________________________________
void TStFmsHotChDB::Streamer(TBuffer &R__b)
{
   // Stream an object of class TStFmsHotChDB.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b.CheckByteCount(R__s, R__c, TStFmsHotChDB::IsA());
   } else {
      R__c = R__b.WriteVersion(TStFmsHotChDB::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TStFmsHotChDB::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TStFmsHotChDB.
      TClass *R__cl = ::TStFmsHotChDB::IsA();
      if (R__cl || R__insp.IsA()) { }
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_TStFmsHotChDB(void *p) {
      return  p ? new(p) ::TStFmsHotChDB : new ::TStFmsHotChDB;
   }
   static void *newArray_TStFmsHotChDB(Long_t nElements, void *p) {
      return p ? new(p) ::TStFmsHotChDB[nElements] : new ::TStFmsHotChDB[nElements];
   }
   // Wrapper around operator delete
   static void delete_TStFmsHotChDB(void *p) {
      delete ((::TStFmsHotChDB*)p);
   }
   static void deleteArray_TStFmsHotChDB(void *p) {
      delete [] ((::TStFmsHotChDB*)p);
   }
   static void destruct_TStFmsHotChDB(void *p) {
      typedef ::TStFmsHotChDB current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_TStFmsHotChDB(TBuffer &buf, void *obj) {
      ((::TStFmsHotChDB*)obj)->::TStFmsHotChDB::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::TStFmsHotChDB

/********************************************************
* libDiffAnalysis_Dict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablelibDiffAnalysis_Dict();

extern "C" void G__set_cpp_environmentlibDiffAnalysis_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("./DiffJetXFCalc_Inc.h");
  G__add_compiledheader("./DiffJetXFANCalc_6pt_Inc.h");
  G__add_compiledheader("./RunDiffJetTreeMaker_zerobias.h");
  G__add_compiledheader("./TStFmsHotChDB.h");
  G__add_compiledheader("./DiffJetXFCalc_EastRPnew.h");
  G__add_compiledheader("./TStRunList.h");
  G__add_compiledheader("./DiffJetXFANCalc_6pt_East_getChi2AndConst.h");
  G__add_compiledheader("./DiffJetAnaTreeQaRun15New.h");
  G__add_compiledheader("./DiffJetXFANCalc_6pt_East.h");
  G__add_compiledheader("./DiffJetXFCalc_WestRPnew.h");
  G__add_compiledheader("./DiffJetXFANCalc_6pt_RG.h");
  G__add_compiledheader("./RunDiffJetTreeMaker_FMS.h");
  G__add_compiledheader("./RunDiffJetTreeMaker.h");
  G__add_compiledheader("./DiffJetXFANCalc_6pt_SE.h");
  G__cpp_reset_tagtablelibDiffAnalysis_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevlibDiffAnalysis_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TStFmsHotChDB */
static int G__libDiffAnalysis_Dict_184_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TStFmsHotChDB* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TStFmsHotChDB[n];
     } else {
       p = new((void*) gvp) TStFmsHotChDB[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TStFmsHotChDB;
     } else {
       p = new((void*) gvp) TStFmsHotChDB;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TStFmsHotChDB));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict_184_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
  struct G__aRyp1 { Bool_t a[1][571]; }* G__Ap1 = (struct G__aRyp1*) G__int(libp->para[1]);
      ((TStFmsHotChDB*) G__getstructoffset())->GetHotChList((Int_t) G__int(libp->para[0]), G__Ap1->a);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict_184_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TStFmsHotChDB::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict_184_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TStFmsHotChDB::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict_184_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TStFmsHotChDB::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict_184_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TStFmsHotChDB::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict_184_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TStFmsHotChDB*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict_184_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TStFmsHotChDB::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict_184_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TStFmsHotChDB::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict_184_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TStFmsHotChDB::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict_184_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TStFmsHotChDB::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__libDiffAnalysis_Dict_184_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TStFmsHotChDB* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TStFmsHotChDB(*(TStFmsHotChDB*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TStFmsHotChDB));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TStFmsHotChDB G__TTStFmsHotChDB;
static int G__libDiffAnalysis_Dict_184_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TStFmsHotChDB*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TStFmsHotChDB*) (soff+(sizeof(TStFmsHotChDB)*i)))->~G__TTStFmsHotChDB();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TStFmsHotChDB*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TStFmsHotChDB*) (soff))->~G__TTStFmsHotChDB();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__libDiffAnalysis_Dict_184_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TStFmsHotChDB* dest = (TStFmsHotChDB*) G__getstructoffset();
   *dest = *(TStFmsHotChDB*) libp->para[0].ref;
   const TStFmsHotChDB& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* TStRunList */
static int G__libDiffAnalysis_Dict_188_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TStRunList* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TStRunList[n];
     } else {
       p = new((void*) gvp) TStRunList[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TStRunList;
     } else {
       p = new((void*) gvp) TStRunList;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TStRunList));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict_188_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TStRunList::GetRunFromFileName(*((string*) G__int(libp->para[0])), *((const string*) G__int(libp->para[1]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict_188_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TStRunList::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict_188_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TStRunList::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict_188_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TStRunList::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict_188_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TStRunList::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict_188_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TStRunList*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict_188_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TStRunList::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict_188_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TStRunList::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict_188_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TStRunList::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict_188_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TStRunList::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__libDiffAnalysis_Dict_188_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TStRunList* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TStRunList(*(TStRunList*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TStRunList));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TStRunList G__TTStRunList;
static int G__libDiffAnalysis_Dict_188_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TStRunList*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TStRunList*) (soff+(sizeof(TStRunList)*i)))->~G__TTStRunList();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TStRunList*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TStRunList*) (soff))->~G__TTStRunList();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__libDiffAnalysis_Dict_188_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TStRunList* dest = (TStRunList*) G__getstructoffset();
   *dest = *(TStRunList*) libp->para[0].ref;
   const TStRunList& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */
static int G__libDiffAnalysis_Dict__0_2286(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      DiffJetXFCalc_Inc(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      DiffJetXFCalc_Inc(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      DiffJetXFCalc_Inc(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2287(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      DiffJetXFANCalc_6pt_Inc(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3]))
, *((TString*) G__int(libp->para[4])));
      G__setnull(result7);
      break;
   case 4:
      DiffJetXFANCalc_6pt_Inc(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3])));
      G__setnull(result7);
      break;
   case 3:
      DiffJetXFANCalc_6pt_Inc(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      DiffJetXFANCalc_6pt_Inc(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      DiffJetXFANCalc_6pt_Inc(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2288(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      RunDiffJetTreeMaker_zerobias(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, (Int_t) G__int(libp->para[2]), *((TString*) G__int(libp->para[3]))
, (Bool_t) G__int(libp->para[4]));
      G__setnull(result7);
      break;
   case 4:
      RunDiffJetTreeMaker_zerobias(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, (Int_t) G__int(libp->para[2]), *((TString*) G__int(libp->para[3])));
      G__setnull(result7);
      break;
   case 3:
      RunDiffJetTreeMaker_zerobias(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, (Int_t) G__int(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      RunDiffJetTreeMaker_zerobias(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      RunDiffJetTreeMaker_zerobias(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   case 0:
      RunDiffJetTreeMaker_zerobias();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2289(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      DiffJetXFCalc_EastRPnew(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3]))
, *((TString*) G__int(libp->para[4])));
      G__setnull(result7);
      break;
   case 4:
      DiffJetXFCalc_EastRPnew(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3])));
      G__setnull(result7);
      break;
   case 3:
      DiffJetXFCalc_EastRPnew(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      DiffJetXFCalc_EastRPnew(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      DiffJetXFCalc_EastRPnew(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2291(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      DiffJetXFANCalc_6pt_East_getChi2AndConst(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3]))
, *((TString*) G__int(libp->para[4])));
      G__setnull(result7);
      break;
   case 4:
      DiffJetXFANCalc_6pt_East_getChi2AndConst(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3])));
      G__setnull(result7);
      break;
   case 3:
      DiffJetXFANCalc_6pt_East_getChi2AndConst(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      DiffJetXFANCalc_6pt_East_getChi2AndConst(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      DiffJetXFANCalc_6pt_East_getChi2AndConst(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2292(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      DiffJetAnaTreeQaRun15New(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3])));
      G__setnull(result7);
      break;
   case 3:
      DiffJetAnaTreeQaRun15New(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      DiffJetAnaTreeQaRun15New(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      DiffJetAnaTreeQaRun15New(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2293(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      DiffJetXFANCalc_6pt_East(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3]))
, *((TString*) G__int(libp->para[4])));
      G__setnull(result7);
      break;
   case 4:
      DiffJetXFANCalc_6pt_East(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3])));
      G__setnull(result7);
      break;
   case 3:
      DiffJetXFANCalc_6pt_East(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      DiffJetXFANCalc_6pt_East(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      DiffJetXFANCalc_6pt_East(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2294(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      DiffJetXFCalc_WestRPnew(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3])));
      G__setnull(result7);
      break;
   case 3:
      DiffJetXFCalc_WestRPnew(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      DiffJetXFCalc_WestRPnew(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      DiffJetXFCalc_WestRPnew(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2295(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      DiffJetXFANCalc_6pt_RG(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3]))
, *((TString*) G__int(libp->para[4])));
      G__setnull(result7);
      break;
   case 4:
      DiffJetXFANCalc_6pt_RG(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3])));
      G__setnull(result7);
      break;
   case 3:
      DiffJetXFANCalc_6pt_RG(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      DiffJetXFANCalc_6pt_RG(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      DiffJetXFANCalc_6pt_RG(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2296(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      RunDiffJetTreeMaker_FMS(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, (Int_t) G__int(libp->para[2]), *((TString*) G__int(libp->para[3]))
, (Bool_t) G__int(libp->para[4]));
      G__setnull(result7);
      break;
   case 4:
      RunDiffJetTreeMaker_FMS(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, (Int_t) G__int(libp->para[2]), *((TString*) G__int(libp->para[3])));
      G__setnull(result7);
      break;
   case 3:
      RunDiffJetTreeMaker_FMS(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, (Int_t) G__int(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      RunDiffJetTreeMaker_FMS(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      RunDiffJetTreeMaker_FMS(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   case 0:
      RunDiffJetTreeMaker_FMS();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2297(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      RunDiffJetTreeMaker(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, (Int_t) G__int(libp->para[2]), *((TString*) G__int(libp->para[3]))
, (Bool_t) G__int(libp->para[4]));
      G__setnull(result7);
      break;
   case 4:
      RunDiffJetTreeMaker(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, (Int_t) G__int(libp->para[2]), *((TString*) G__int(libp->para[3])));
      G__setnull(result7);
      break;
   case 3:
      RunDiffJetTreeMaker(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, (Int_t) G__int(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      RunDiffJetTreeMaker(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      RunDiffJetTreeMaker(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   case 0:
      RunDiffJetTreeMaker();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2298(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      DiffJetXFANCalc_6pt_SE(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3]))
, *((TString*) G__int(libp->para[4])));
      G__setnull(result7);
      break;
   case 4:
      DiffJetXFANCalc_6pt_SE(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3])));
      G__setnull(result7);
      break;
   case 3:
      DiffJetXFANCalc_6pt_SE(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      DiffJetXFANCalc_6pt_SE(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      DiffJetXFANCalc_6pt_SE(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}


/*********************************************************
* Member function Stub
*********************************************************/

/* TStFmsHotChDB */

/* TStRunList */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfunclibDiffAnalysis_Dict {
 public:
  G__Sizep2memfunclibDiffAnalysis_Dict(): p(&G__Sizep2memfunclibDiffAnalysis_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfunclibDiffAnalysis_Dict::*p)();
};

size_t G__get_sizep2memfunclibDiffAnalysis_Dict()
{
  G__Sizep2memfunclibDiffAnalysis_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancelibDiffAnalysis_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TStFmsHotChDB))) {
     TStFmsHotChDB *G__Lderived;
     G__Lderived=(TStFmsHotChDB*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TStFmsHotChDB),G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TStRunList))) {
     TStRunList *G__Lderived;
     G__Lderived=(TStRunList*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TStRunList),G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablelibDiffAnalysis_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TStFmsHotChDB */
static void G__setup_memvarTStFmsHotChDB(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TStFmsHotChDB));
   { TStFmsHotChDB *p; p=(TStFmsHotChDB*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* TStRunList */
static void G__setup_memvarTStRunList(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TStRunList));
   { TStRunList *p; p=(TStRunList*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TEntryList),-1,-1,4,"runList=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TEntryList),-1,-1,4,"missingRunList=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarlibDiffAnalysis_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTStFmsHotChDB(void) {
   /* TStFmsHotChDB */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TStFmsHotChDB));
   G__memfunc_setup("TStFmsHotChDB",1181,G__libDiffAnalysis_Dict_184_0_1, 105, G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TStFmsHotChDB), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHotChList",1170,G__libDiffAnalysis_Dict_184_0_2, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - fillNo G - 'Bool_t' 2 - isHotCh", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__libDiffAnalysis_Dict_184_0_3, 85, G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TStFmsHotChDB::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__libDiffAnalysis_Dict_184_0_4, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TStFmsHotChDB::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__libDiffAnalysis_Dict_184_0_5, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TStFmsHotChDB::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__libDiffAnalysis_Dict_184_0_6, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TStFmsHotChDB::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__libDiffAnalysis_Dict_184_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__libDiffAnalysis_Dict_184_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TStFmsHotChDB::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__libDiffAnalysis_Dict_184_0_12, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TStFmsHotChDB::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__libDiffAnalysis_Dict_184_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TStFmsHotChDB::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__libDiffAnalysis_Dict_184_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TStFmsHotChDB::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TStFmsHotChDB", 1181, G__libDiffAnalysis_Dict_184_0_15, (int) ('i'), G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TStFmsHotChDB), -1, 0, 1, 1, 1, 0, "u 'TStFmsHotChDB' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TStFmsHotChDB", 1307, G__libDiffAnalysis_Dict_184_0_16, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__libDiffAnalysis_Dict_184_0_17, (int) ('u'), G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TStFmsHotChDB), -1, 1, 1, 1, 1, 0, "u 'TStFmsHotChDB' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncTStRunList(void) {
   /* TStRunList */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TStRunList));
   G__memfunc_setup("TStRunList",1004,G__libDiffAnalysis_Dict_188_0_1, 105, G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TStRunList), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetRunFromFileName",1770,G__libDiffAnalysis_Dict_188_0_2, 105, -1, G__defined_typename("Int_t"), 0, 2, 3, 1, 0, 
"u 'string' - 0 - fileName u 'string' - 10 - prefix", (char*)NULL, (void*) G__func2void( (Int_t (*)(string, const string))(&TStRunList::GetRunFromFileName) ), 0);
   G__memfunc_setup("Class",502,G__libDiffAnalysis_Dict_188_0_3, 85, G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TStRunList::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__libDiffAnalysis_Dict_188_0_4, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TStRunList::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__libDiffAnalysis_Dict_188_0_5, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TStRunList::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__libDiffAnalysis_Dict_188_0_6, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TStRunList::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__libDiffAnalysis_Dict_188_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__libDiffAnalysis_Dict_188_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TStRunList::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__libDiffAnalysis_Dict_188_0_12, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TStRunList::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__libDiffAnalysis_Dict_188_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TStRunList::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__libDiffAnalysis_Dict_188_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TStRunList::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TStRunList", 1004, G__libDiffAnalysis_Dict_188_0_15, (int) ('i'), G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TStRunList), -1, 0, 1, 1, 1, 0, "u 'TStRunList' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TStRunList", 1130, G__libDiffAnalysis_Dict_188_0_16, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__libDiffAnalysis_Dict_188_0_17, (int) ('u'), G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_TStRunList), -1, 1, 1, 1, 1, 0, "u 'TStRunList' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfunclibDiffAnalysis_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globallibDiffAnalysis_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
   G__memfunc_setup("DiffJetXFCalc_Inc", 1574, G__libDiffAnalysis_Dict__0_2286, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"DiffJetXFPlot.root\"' outName "
"u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("DiffJetXFANCalc_6pt_Inc", 2094, G__libDiffAnalysis_Dict__0_2287, 121, -1, -1, 0, 5, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"DiffJetXFANCalc_6pt_Inc.root\"' outName "
"u 'TString' - 0 '\"DiffJetXFANCalc_6pt_Inc.txt\"' outNameText u 'TString' - 0 '\"all\"' photon "
"u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("RunDiffJetTreeMaker_zerobias", 2831, G__libDiffAnalysis_Dict__0_2288, 121, -1, -1, 0, 5, 1, 1, 0, 
"u 'TString' - 0 '\"./inFiles_fms.list\"' inFile u 'TString' - 0 '\"jets.root\"' outFile "
"i - 'Int_t' 0 '18857' fillNumber u 'TString' - 0 '\"fms\"' det "
"g - 'Bool_t' 0 'kFALSE' isMC", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("DiffJetXFCalc_EastRPnew", 2181, G__libDiffAnalysis_Dict__0_2289, 121, -1, -1, 0, 5, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"DiffJetXFPlot.root\"' outName "
"u 'TString' - 0 '\"AN\"' mode u 'TString' - 0 '\"SD\"' process "
"u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("DiffJetXFANCalc_6pt_East_getChi2AndConst", 3744, G__libDiffAnalysis_Dict__0_2291, 121, -1, -1, 0, 5, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"DiffJetXFANCalc_6pt_East_Chi2AndConst.txt\"' outNameText "
"u 'TString' - 0 '\"all\"' photon u 'TString' - 0 '\"SD\"' process "
"u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("DiffJetAnaTreeQaRun15New", 2227, G__libDiffAnalysis_Dict__0_2292, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"DiffJetAnaQa.root\"' outName "
"u 'TString' - 0 '\"SD\"' process u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("DiffJetXFANCalc_6pt_East", 2209, G__libDiffAnalysis_Dict__0_2293, 121, -1, -1, 0, 5, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"DiffJetXFANCalc_6pt_East.root\"' outName "
"u 'TString' - 0 '\"DiffJetXFANCalc_6pt_East.txt\"' outNameText u 'TString' - 0 '\"all\"' photon "
"u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("DiffJetXFCalc_WestRPnew", 2203, G__libDiffAnalysis_Dict__0_2294, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"DiffJetXFPlot.root\"' outName "
"u 'TString' - 0 '\"AN\"' mode u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("DiffJetXFANCalc_6pt_RG", 1965, G__libDiffAnalysis_Dict__0_2295, 121, -1, -1, 0, 5, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"DiffJetXFANCalc_6pt_RG.root\"' outName "
"u 'TString' - 0 '\"DiffJetXFANCalc_6pt_RG.txt\"' outNameText u 'TString' - 0 '\"all\"' photon "
"u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("RunDiffJetTreeMaker_FMS", 2198, G__libDiffAnalysis_Dict__0_2296, 121, -1, -1, 0, 5, 1, 1, 0, 
"u 'TString' - 0 '\"./inFiles_fms.list\"' inFile u 'TString' - 0 '\"jets.root\"' outFile "
"i - 'Int_t' 0 '18857' fillNumber u 'TString' - 0 '\"fms\"' det "
"g - 'Bool_t' 0 'kFALSE' isMC", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("RunDiffJetTreeMaker", 1873, G__libDiffAnalysis_Dict__0_2297, 121, -1, -1, 0, 5, 1, 1, 0, 
"u 'TString' - 0 '\"./inFiles_fms.list\"' inFile u 'TString' - 0 '\"jets.root\"' outFile "
"i - 'Int_t' 0 '18857' fillNumber u 'TString' - 0 '\"fms\"' det "
"g - 'Bool_t' 0 'kFALSE' isMC", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("DiffJetXFANCalc_6pt_SE", 1964, G__libDiffAnalysis_Dict__0_2298, 121, -1, -1, 0, 5, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"DiffJetXFANCalc_6pt_SE.root\"' outName "
"u 'TString' - 0 '\"DiffJetXFANCalc_6pt_SE.txt\"' outNameText u 'TString' - 0 '\"all\"' photon "
"u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funclibDiffAnalysis_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__libDiffAnalysis_DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__libDiffAnalysis_DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__libDiffAnalysis_DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__libDiffAnalysis_DictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__libDiffAnalysis_DictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__libDiffAnalysis_DictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__libDiffAnalysis_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__libDiffAnalysis_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__libDiffAnalysis_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__libDiffAnalysis_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__libDiffAnalysis_DictLN_TStFmsHotChDB = { "TStFmsHotChDB" , 99 , -1 };
G__linked_taginfo G__libDiffAnalysis_DictLN_TEntryList = { "TEntryList" , 99 , -1 };
G__linked_taginfo G__libDiffAnalysis_DictLN_TStRunList = { "TStRunList" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablelibDiffAnalysis_Dict() {
  G__libDiffAnalysis_DictLN_TClass.tagnum = -1 ;
  G__libDiffAnalysis_DictLN_TBuffer.tagnum = -1 ;
  G__libDiffAnalysis_DictLN_TMemberInspector.tagnum = -1 ;
  G__libDiffAnalysis_DictLN_TObject.tagnum = -1 ;
  G__libDiffAnalysis_DictLN_TString.tagnum = -1 ;
  G__libDiffAnalysis_DictLN_string.tagnum = -1 ;
  G__libDiffAnalysis_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__libDiffAnalysis_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__libDiffAnalysis_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__libDiffAnalysis_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__libDiffAnalysis_DictLN_TStFmsHotChDB.tagnum = -1 ;
  G__libDiffAnalysis_DictLN_TEntryList.tagnum = -1 ;
  G__libDiffAnalysis_DictLN_TStRunList.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablelibDiffAnalysis_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__libDiffAnalysis_DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__libDiffAnalysis_DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__libDiffAnalysis_DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__libDiffAnalysis_DictLN_TObject);
   G__get_linked_tagnum_fwd(&G__libDiffAnalysis_DictLN_TString);
   G__get_linked_tagnum_fwd(&G__libDiffAnalysis_DictLN_string);
   G__get_linked_tagnum_fwd(&G__libDiffAnalysis_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__libDiffAnalysis_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__libDiffAnalysis_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__libDiffAnalysis_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__libDiffAnalysis_DictLN_TStFmsHotChDB),sizeof(TStFmsHotChDB),-1,29952,(char*)NULL,G__setup_memvarTStFmsHotChDB,G__setup_memfuncTStFmsHotChDB);
   G__get_linked_tagnum_fwd(&G__libDiffAnalysis_DictLN_TEntryList);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__libDiffAnalysis_DictLN_TStRunList),sizeof(TStRunList),-1,29952,(char*)NULL,G__setup_memvarTStRunList,G__setup_memfuncTStRunList);
}
extern "C" void G__cpp_setuplibDiffAnalysis_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setuplibDiffAnalysis_Dict()");
  G__set_cpp_environmentlibDiffAnalysis_Dict();
  G__cpp_setup_tagtablelibDiffAnalysis_Dict();

  G__cpp_setup_inheritancelibDiffAnalysis_Dict();

  G__cpp_setup_typetablelibDiffAnalysis_Dict();

  G__cpp_setup_memvarlibDiffAnalysis_Dict();

  G__cpp_setup_memfunclibDiffAnalysis_Dict();
  G__cpp_setup_globallibDiffAnalysis_Dict();
  G__cpp_setup_funclibDiffAnalysis_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfunclibDiffAnalysis_Dict();
  return;
}
class G__cpp_setup_initlibDiffAnalysis_Dict {
  public:
    G__cpp_setup_initlibDiffAnalysis_Dict() { G__add_setup_func("libDiffAnalysis_Dict",(G__incsetup)(&G__cpp_setuplibDiffAnalysis_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initlibDiffAnalysis_Dict() { G__remove_setup_func("libDiffAnalysis_Dict"); }
};
G__cpp_setup_initlibDiffAnalysis_Dict G__cpp_setup_initializerlibDiffAnalysis_Dict;

